# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Actions Checkout
        uses: actions/checkout@v3
      - name: Flutter Actions
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.5'
      - name: Get dependencies
        run: flutter pub get
      - name: Build Web dependencies
        run: flutter build web
  

